### ISSUE TITLE
__builtin_cpu_is not defined on non x86 systems

### ISSUE THREAD

**Issue by Tratori** [jmuehlig/perf-cpp#3]
Hello Jan,

This project looks great, the API is very intuitive - thank you for writing this.

When I attempt to compile v0.7.0 on ARM, I unfortunately get the error that __builtin_cpu_is() is not defined (only x86 builtin).
I'm not very familiar with detecting CPUs/Architecture automatically, so simply always return 0 on non-x86 systems as a dirty fix (https://github.com/Tratori/perf-cpp/commit/2f51bf53a786a4ea634c1095032923675339b720), which makes it useable again. 

Are there any plans to maintain ARM compatibility (the focus is Intel and AMD right now)?

Greetings,
Fabian

**Comment by jmuehlig** [comment]
Hi Fabian, I'm glad to hear you liked it!

I wasn't aware that ARM compilers don't support `__builtin_cpu_is`. Could you please submit your fix as a pull request? We can then push out a bug-fix release.

As for the ARM plans, I'm definitely interested in working on that. However, I currently don't have access to an ARM system with SPE implementation, but it's certainly on my TODO list.

Best,
Jan
